Registry.start_link(keys: :duplicate, name: :viewport_registry)
Registry.start_link(keys: :duplicate, name: :input_registry)
Registry.start_link(keys: :duplicate, name: :driver_registry)
Scenic.Cache.Support.Supervisor.start_link()
ExUnit.start()
