Registry.start_link(keys: :duplicate, name: :scenic_cache_registry)
Registry.start_link(keys: :duplicate, name: :viewport_registry)
Registry.start_link(keys: :duplicate, name: :input_registry)
Registry.start_link(keys: :duplicate, name: :driver_registry)
ExUnit.start()
