name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    name: PR Title
    runs-on: ubuntu-latest

    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        max_length: 64 # Max length of the title
        github_token: ${{ github.token }} # Default: ${{ github.token }}
